### ISSUE TITLE
The 'is_significant' variable missing reference

### ISSUE THREAD

**Issue by bmroger2** [jpquast/protti#155]
Hello!

I am continually very pleased with the output and readability of this vignette but I noticed something confusing : the bottom of the single dose treatment (this corresponds to data that I am working on) contains a section called 'Additional helpful functions'. The third paragraph references one to use 'is_significant' and then it is indeed used in the corresponding diff_abundance_significant code but is not created in this workflow. The 'is_significant' column is only found / created in the dose response data analysis workflow. However, the 'is_significant' variable calls for a 'passed_filter' variable also not present in the single dose workflow. In fact, I can't seem to find the 'passed_filter' variable at all. 

Kind regards, 
Bryan

**Comment by jpquast** [comment]
Hi Bryan,

thanks a lot for your continual feedback! It's very helpful because it helps us to improve the package.
I will make the use of these variables more clear in both vignettes and also show how they are created. You can also always check the function documentation for the function that uses them, but I think it might not be that clear either. 

The `is_significant` column in your data frame should be a logical column that means it contains only `TRUE` or `FALSE`. It is created by setting cutoffs for the significance and fold change that you consider significant. That means e.g. that you consider all peptides or proteins in your experiment significant that are having at least an absolute log2 fold change of 1  and an adjusted p-value of 0.05 or below. 

You can thus create the `is_significant` column as follows:
`data_frame_modified <- mutate(data_frame, is_significant = ifelse(abs(diff) >= 1 & adj_pval <= 0.05, TRUE, FALSE))`

Let me know if something is not clear or does not work.
All the best,
JP

**Comment by bmroger2** [comment]
Thank you for the additional explanation! 

Kind regards, 
Bryan
