### ISSUE TITLE
calculate_diff_abundance output can't add intensity_log2 column

### ISSUE THREAD

**Issue by the8thday** [jpquast/protti#178]
Hi,
the calculate_diff_abundance() function can't retain the intensity_log2=normalised_intensity_log2 column in output, even i add normalised_intensity_log2 to retain_columns=c(genes, sampleID, normalised_intensity_log2), is there a way to do this ?

Thanks!

**Comment by jpquast** [comment]
Hi, 
thanks for raising this issue! This was indeed not possible due to some internal filtering. I rewrote this part of the function now and will submit this to CRAN as soon as possible. I hope this will be updated on GitHub later today or tomorrow. 

I am sure you are aware of this but please note that by retaining the intensity values you will duplicate rows in the output data frame. This is because there are of course multiple intensity values associated with with each test result.

**Comment by the8thday** [comment]
Hi, Quast:
Thanks for the quick replay! i indeed know duplicated rows will there in the output data, but i want the normalized intensity value in the output too, this will an overview as i designed concentration gradient experiments. Also i can use pivot_wider to transform long data to wider data. 
please forgive my poor english!

thanks again for your great work!

**Comment by the8thday** [comment]
Hi Jan:
have you ever modified the function? i had re-install protti through github, but nothing changed. The output of calculate_diff_abundance() still can't add intensity_log2=normalised_intensity_log2 column.
Thanks a lot!

CongLiu

**Comment by dschust-r** [comment]
Hi there, 
We are working on it but unfortunately have not implemented the changes on CRAN yet. We hope to be able to do this in the upcoming week. Sorry for the delay and the inconvenience!

Dina

**Comment by jpquast** [comment]
You can actually install the "Small Fixes" branch directly with the "ref" argument of "devtools::install_github()". There are only minor fixes that I still need to do before it is joined into the master. Sorry about the inconvenience.

**Comment by the8thday** [comment]
Dear Jan, Dear Dina:
Thank you for your prompt response!  Thank you very much !

**Comment by jpquast** [comment]
The new protti version is now also available on CRAN.
