### ISSUE TITLE
go_enrichment does not work

### ISSUE THREAD

**Issue by dschust-r** [jpquast/protti#76]
When using `go_enrichment(data, uniprot_id,  is_significant = significant, ontology_type = "CC", organism_id = "9606", algorithm = "elim", statistic = "fisher"`)
error: 
`Fehler in get(paste("GO", whichOnto, "Term", sep = "")) : 
  Objekt 'GOCCTerm' nicht gefunden`

similar error for other GO terms;

typo in roxygen header (arguments, ontology type - biological process (**BP**))
comma missing in example (after `is_significant = significant`)

**Comment by jpquast** [comment]
Calling `library(topGO)` resolves issue. 

I will try to find out which dependency is not properly loaded.

**Comment by jpquast** [comment]
The problem was that topGO runs `topGO::groupGOTerms` upon loading the package with `library(topGO)`. This function creates three environments in the package environment that are called `GOCCTerm`, `GOMFTerm` and `GOBPTerm`. These contain go annotations for these specific processes. When certain `topGO` functions were used in the package without attachment of `topGO` the environments were not created and thus not usable. This caused the error. 
With pull request #93 `topGO` was removed from the `go_enrichment` function and replaced by a simple two-sided fishers exact test.
